### ISSUE TITLE
npm run test

### ISSUE THREAD

**Issue by styfle** [locnguyen/typescript-node-starter#18]
Great project! I especially like your Dockerfile using the multi-stage feature. I have a similar project called [react-server-example-tsx](https://github.com/styfle/react-server-example-tsx).

I noticed that execute `npm run build` but not `npm run test` in the Dockerfile. Where do you run tests? Is it assumed tests are run before docker build?

**Comment by locnguyen** [comment]
@styfle I run prettier, tslint, and execute tests outside of the image building process. I'm definitely not an expert on the ops-y side of things but this has worked out so far for me. Check out the GitLab CI yaml file to see
