### ISSUE TITLE
Update to TypeScript 2.7

### ISSUE THREAD

**Issue by locnguyen** [locnguyen/typescript-node-starter#22]
Just released this week: https://github.com/Microsoft/TypeScript/releases/tag/v2.7.1

**Comment by locnguyen** [comment]
What's wrong with this maintainer? TypeScript is at version 8 already :)

**Comment by styfle** [comment]
Take a peek at [react-server-example-tsx](https://github.com/styfle/react-server-example-tsx) for the latest and greatest 😉
